webui/Models/CartIndexViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }

    }
}

webui/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class LoginViewModel
    {
        [Required]
        public string UserName { get; set; }

        [Required]
        public string Password { get; set; }
    }
}

webui/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages { get
                    {
                        return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage);
                    }}

    }
}

webui/Models/ProductsListViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

webui/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Infrastructure.Abstract;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class AccountController : Controller
    {
        IAuthProvider authProvider;

        public AccountController(IAuthProvider auth)
        { authProvider = auth; }

        public ViewResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (authProvider.Authenticate(model.UserName, model.Password))
                    return Redirect(returnUrl ?? Url.Action("Index", "Admin"));
                
                ModelState.AddModelError("", "Incorrect username or password");
            }

            return View();
        }
    }
}

webui/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Entities;

namespace WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private IProductsRepository repository;
        
        public AdminController(IProductsRepository repo)
        {
            repository = repo;
        }

        // GET: Admin
        public ViewResult Index()
        {
            return View(repository.Products);
        }

        public ViewResult Edit(int productId)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);

            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                repository.SaveProduct(product);
                TempData["message"] = string.Format("{0} has been saved", product.Name);

                return RedirectToAction("Index");
            }
            
            return View(product); 
        }

        public ViewResult Create()
        {
            return View("Edit", new Product());
        }

        [HttpPost]
        public ActionResult Delete(int productId)
        {
            Product deletedProduct = repository.DeleteProduct(productId);
            if (deletedProduct != null)
            {
                TempData["message"] = string.Format("{0} was deleted", deletedProduct.Name);
            }

            return RedirectToAction("Index");
        }

    }
}

webui/Controllers/CartController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductsRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IProductsRepository repo, IOrderProcessor order)
        { repository = repo; orderProcessor = order;  }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel { Cart = cart, ReturnUrl = returnUrl });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
                cart.AddItem(product, 1);

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
                cart.RemoveLine(product);

            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            
            return View(shippingDetails);
        }
    }
}

webui/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;

namespace WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductsRepository repository;

        public NavController(IProductsRepository repo)
        {
            repository = repo;
        }
        public PartialViewResult Menu(string p_category = null)
        {
            IEnumerable<string> categories = repository.Products.Select(x => x.Category).Distinct().OrderBy(x => x);
            ViewBag.SelectedCategory = p_category;

            return PartialView("FlexMenu", categories);
        }
    }
}

webui/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Entities;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductsRepository repository;
        public int PageSize = 4;

        public ProductController(IProductsRepository productRepository)
        {
            this.repository = productRepository;
        }

        // GET: Product
        public ViewResult List(string p_category, int p_page = 1)
        {
            
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = repository.Products.Where(p => p_category == null || p.Category == p_category).OrderBy(p => p.ProductID).Skip((p_page - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = p_page,
                    ItemsPerPage = PageSize,
                    TotalItems = (p_category == null ? repository.Products.Count() : repository.Products.Where(e => e.Category == p_category).Count())
                },
                CurrentCategory = p_category
            };

            return View(model);
        }
    }
}

webui/Views/Admin/Edit.cshtml
@model Domain.Entities.Product

@{
    ViewBag.Title = "Edit - " + Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Admin"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

webui/Views/Admin/Index.cshtml
@model IEnumerable<Domain.Entities.Product>

@{
    ViewBag.Title = "All Products";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class ="panel panel-default" > 
    <div class ="panel-heading"> 
        <h3> All Products </h3> 
    </div > 
    <div class="panel-body"> 
        <table class="table table-striped table-condensed table-bordered"> 
            <tr>
                <th class="text-right"> ID </th>
                <th> Name </th> 
                <th class="text-right"> Price </th> 
                <th class="text-center"> Actions </th>
            </tr> 
            @foreach (var item in Model)
            { 
                <tr> 
                    <td class="text-right"> @item.ProductID </td> 
                    <td>@Html.ActionLink(item.Name, "Edit", new { item.ProductID }) </td>
                    <td class="text-right">@item.Price.ToString("c") </td> 
                    <td class ="text-center">
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            @Html.Hidden("ProductID", item.ProductID) 
                            <input type="submit" class="btn btn-default btn-xs" value="Delete"/> 
                        } 
                    </td> 
                </tr> 
            } 
        </table> 
    </div> 
    <div class="panel-footer"> 
        @Html.ActionLink("Add a new product", "Create", null, new { @class = "btn btn-default" })
    </div>
</div>

webui/Views/Cart/Checkout.cshtml
@model Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "Checkout";
}

<h2> Check out now </h2> 
<p> Please enter your details, and we'll ship your goods right away! </p> 
@using (Html.BeginForm())
{ 
    @Html.ValidationSummary()
    <h3> Ship to </h3> 
    <div class="form-group"> 
        <label> Name: </label> 
        @Html.TextBoxFor(x => x.Name, new { @class="form-control" }) 
    </div>  
    <h3> Address </h3>

    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName != "Name" && property.PropertyName != "GiftWrap")
        { 
            <div class="form-group"> 
                <label>@(property.DisplayName ?? property.PropertyName) </label> 
                @Html.TextBox(property.PropertyName, null, new { @class="form-control" }) 
            </div>
        }
    }

    <h3> Options </h3> 
    <div class="checkbox"> 
        <label> @Html.EditorFor(x => x.GiftWrap) Gift wrap these items </label> 
    </div>
    <div class="text-center"> 
        <input class="btn btn-primary" type="submit" value="Complete order"/> 
    </div>
}

webui/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Order Submitted";
}

<h2> Thanks! </h2> 
Thanks for placing your order. We'll ship your goods as soon as possible.

webui/Views/Cart/Index.cshtml
@model WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "Your Cart";
}

<style>
    #cartTable td { vertical-align: middle; }
</style>

<h2> Your cart </h2> 
    <table id="cartTable" class="table">
        <thead> 
            <tr>
                
                <th class="text-center"> Quantity </th>
                <th> Item </th>
                <th class="text-right"> Price </th> 
                <th class="text-right"> Subtotal </th> 
            </tr> 
        </thead> 
        <tbody> 
            @foreach (var line in Model.Cart.Lines)
            {
                <tr>                     
                    <td class="text-center">@line.Quantity</td> 
                    <td class="text-left" >@line.Product.Name</td>
                    <td class="text-right">@line.Product.Price.ToString("c")</td>
                    <td class="text-right">@((line.Quantity * line.Product.Price).ToString("c"))</td> 
                    <td class="text-left">
                        @using (Html.BeginForm("RemoveFromCart", "Cart"))
                        {
                            @Html.Hidden("ProductId", line.Product.ProductID)
                            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                            <input type="submit" class="btn btn-sm btn-warning" value="Remove from cart" />
                        }
                    </td>
                </tr> 
            }
         </tbody> 
        <tfoot> 
            <tr> 
                <td colspan="3" class="text-right"> Total: </td>
                <td class="text-right">@Model.Cart.ComputeTotalValue().ToString("c")</td>
             </tr> 
        </tfoot> 
    </table> 
<div class="text-center"> 
    <a class="btn btn-primary" href="@Model.ReturnUrl"> Continue shopping </a>
    @Html.ActionLink("Checkout Now", "Checkout", null, new { @class = "btn btn-primary" })
</div>

webui/Views/Cart/Summary.cshtml
@model Domain.Entities.Cart



<div class="navbar-right hidden-xs">
    @Html.ActionLink("Checkout", "Index", "Cart", new { returnUrl = Request.Url.PathAndQuery }, new { @class = "btn btn-default navbar-btn" }) &emsp;
</div>

<div class="navbar-right visible-xs"> 
    <a href=@Url.Action("Index", "Cart", new { returnUrl = Request.Url.PathAndQuery }) class ="btn btn-default navbar-btn" > 
        <span class="glyphicon glyphicon-shopping-cart"> </span> 
    </a> 
</div>

<div class="navbar-text navbar-right"> 
    <b class="hidden-xs"> Your cart: </b> 
    @Model.Lines.Sum(x => x.Quantity) item(s), @Model.ComputeTotalValue().ToString("c")&emsp;
</div>

webui/Views/Nav/FlexMenu.cshtml
@model IEnumerable<string>

@{ 
    bool horizontal = ((bool)(ViewContext.RouteData.Values["horizontalLayout"] ?? false));
    string wrapperClasses = horizontal ? "btn-group btn-group-sm btn-group-justified" : null; 
} 

<div class ="@wrapperClasses"> 
    @Html.ActionLink("Home", "List", "Product", null, new
            { @class = horizontal ? "btn btn-default btn-sm" : "btn btn-block btn-default btn-lg" }) 
    
    @foreach (var link in Model)
    { 
        @Html.RouteLink(link,
            new { controller = "Product", action = "List", p_category = link, page = 1 },
            new { @class = (horizontal ? "btn btn-default btn-sm" : "btn btn-block btn-default btn-lg")
                    + (link == ViewBag.SelectedCategory ? " btn-primary" : "") }) 
    }
 </div>

webui/Views/Nav/Menu.cshtml
@model IEnumerable<string> 
    
@Html.ActionLink("Home", "List", "Product", null,
    new { @class = "btn btn-block btn-default btn-lg" + (ViewBag.SelectedCategory == "Home" ? " btn-primary" : "")
    })

@foreach(var link in Model)
{ 
    @Html.RouteLink(link, new {
    controller = "Product",
    action = "List",
    p_category = link,
    p_page = 1 },
    new { @class = "btn btn-block btn-default btn-lg"
        + (link == ViewBag.SelectedCategory ? " btn-primary" : "")
        }) 
}

webui/Views/Product/List (Maxime Thomassin's conflicted copy 2016-08-24).cshtml
@using Domain.Entities;
@model WebUI.Models.ProductsListViewModel

@{
    ViewBag.Title = "Products";
}

@foreach (var p in Model.Products)
{
    @Html.Partial("ProductSummary", p)
} 
<div class ="btn-group pull-right" >
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { p_page = x , p_category = Model.CurrentCategory }))
</div>

webui/Views/Product/List.cshtml
@using Domain.Entities;
@model WebUI.Models.ProductsListViewModel

@{
    ViewBag.Title = "Products";
}

@foreach (var p in Model.Products)
{
    @Html.Partial("ProductSummary", p)
} 
<div class ="btn-group pull-right" >
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { p_page = x , p_category = Model.CurrentCategory }))
</div>
<p>
    @ViewBag.Query
</p>

webui/Views/Shared/ProductSummary.cshtml
@model Domain.Entities.Product

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">
            @Model.Price.ToString("c")
        </span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ProductID)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to cart" />
        </div>
    }
    <span class="lead">@Model.Description</span>
</div> 

webui/Views/Shared/_AdminLayout.cshtml
@{ 
    Layout = null;
    HtmlHelper.ClientValidationEnabled = true;
    HtmlHelper.UnobtrusiveJavaScriptEnabled = true;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

webui/Views/Shared/_Layout.cshtml
<! DOCTYPE html> 
<html> 
    <head>
        <meta charset ="utf-8"/> 
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <link href="~/Content/bootstrap.css" rel="stylesheet" />
        <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
        <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
        <title>@ViewBag.Title</title> 
        <style> 
            .navbar-right 
            { 
                float: right !important; 
                margin-right: 15px; 
                margin-left: 15px; 
            }
        </style> 
    </head> 
    <body> 
        <div class="navbar navbar-inverse" role="navigation"> 
            <a class="navbar-brand" href="#" > 
                <span class="hidden-xs" > SPORTS STORE </span> 
                <div class ="visible-xs" > SPORTS </div> 
                <div class ="visible-xs" > STORE </div>
            </a>
            @Html.Action("Summary", "Cart")            
        </div> 

        <div class="visible-xs">
            @Html.Action("Menu", "Nav", new { horizontalLayout = true })
        </div>
        <div class="row panel">
             <div id="categories" class="col-sm-3 hidden-xs"> 
                 @Html.Action("Menu", "Nav")
            </div>
             <div class="col-xs-12 col-sm-8">
                 @RenderBody() 
             </div> 
        </div>

    </body> 
</html>